[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
axum-macros = "0.5.0"
clap = { version = "4.5.53", features = ["derive"] }
shared = { path = "../shared" }
env_logger = "0.11.8"
futures = "0.3.31"
http-body-util = "0.1.3"
hyper = { version = "1.8.1" }
hyper-util = "0.1.19"
hyperlocal = "0.9.1"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = "0.7.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uuid = { version = "1.19.0", features = ["serde", "v4"] }
axum = "0.8.7"
humansize = "2.1.3"
